# Generated by Django 3.1.2 on 2021-01-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExaminationPhoto',
        ),
        migrations.AddField(
            model_name='examination',
            name='photo',
            field=models.ImageField(blank=True, upload_to='scans'),
        ),
    ]
