# Generated by Django 3.1.2 on 2020-12-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dtp', '0002_auto_20201208_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='description',
            field=models.TextField(default='Emtpy', max_length=350),
            preserve_default=False,
        ),
    ]
